routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::post('consultaRol','AuthenticateController@getRolUsuario')->name('consultaRol');//getRolUsuario
Route::post('Authenticate', 'AuthenticateController@Authenticate')->name('Authenticate');

Route::resource('usuarios', 'UsuarioController');
Route::resource('area', 'AreaController');
Route::get('ingreso-area', 'ingresoAreaController@index');
Route::any('ingreso-area/{user}', 'ingresoAreaController@historialIngresoUsuario')->name('historialIngresoUsuario');
Route::get('ingreso-area/lista/usuarios/{ingreso}', 'ingresoAreaController@listaUsuarioIngresoArea');

Route::group(['middleware' => 'jwt.auth'], function () {

	Route::post('ingreso/crear','ingresoAreaController@postIngreso');//getConsultaIngreso
	Route::post('ingreso/consulta','ingresoAreaController@getConsultaIngreso');//getConsultaIngreso
	Route::post('ingreso/consultaPersonal','ingresoAreaController@getConsultaPersonal');//getConsultaPersonal
	

});

app/Http/Controllers/AreaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\AreaModelPostRequest;
use App\AreaModel;


class AreaController extends Controller
{

    public function index()
    {
        $areas = AreaModel::all();
        return view('area.index', compact('areas'));
    }

    public function show(Request $request, AreaModel $area)
    {
        return view('area.show', compact('area'));
    }

    public function create()
    {
        return view('area.create');
    }

    public function store(AreaModelPostRequest $request)
    {
        $data = $request->validated();
        $area = AreaModel::create($data);
        $qrimage= public_path('/qr/area'.$area->id.'.png');
        \QRCode::text($area->id)->setOutfile($qrimage)->png(); 
        return redirect()->route('area.index')->with('status', 'Area created!');
    }

    public function edit(Request $request, AreaModel $area)
    {
        return view('area.edit', compact('area'));
    }

    public function update(AreaModelPostRequest $request, AreaModel $area)
    {
        $data = $request->validated();
        $area->fill($data);
        $area->save();
        if (!is_file(public_path('qr/'.$area->id.'.png'))) {
            $qrimage= public_path('qr/'.$area->id.'.png');
            \QRCode::text($area->id)->setOutfile($qrimage)->png();
        }
         
        return redirect()->route('area.index')->with('status', 'Area actualizada!');
    }

    public function destroy(Request $request, AreaModel $area)
    {
        $area->delete();
        return redirect()->route('area.index')->with('status', 'Area destroyed!');
    }
}

resources/views/area/create.blade.php
@extends('layouts.master')
@section('contenido')
<div class="container">
    <div class="card">

        <div class="header">
            <h3> Crear Area  </h3>
        </div>
        <div class="card-body">

        @if($errors->any())
        <ul>
            @foreach($errors->all() as $error)
            <li class="text-danger">{{ $error }}</li>
            @endforeach
        </ul> @endif <form action="{{route('area.store')}}" method="POST" novalidate>
        {{Form::token()}}
        
                                        <div class="form-group">
            <label for="codigo">Codigo</label>
                        <input class="form-control String"  type="text"  name="codigo" id="codigo" value="{{old('codigo')}}"             maxlength="255"
                                    >
                        @if($errors->has('codigo'))
            <p class="text-danger">{{$errors->first('codigo')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="nombre">Nombre</label>
                        <input class="form-control String"  type="text"  name="nombre" id="nombre" value="{{old('nombre')}}"             maxlength="255"
                                    >
                        @if($errors->has('nombre'))
            <p class="text-danger">{{$errors->first('nombre')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="detalle">Detalle</label>
                        <input class="form-control String"  type="text"  name="detalle" id="detalle" value="{{old('detalle')}}"             maxlength="255"
                                    >
                        @if($errors->has('detalle'))
            <p class="text-danger">{{$errors->first('detalle')}}</p>
            @endif
        </div>
                        <div class="text-right">
            <button class="btn btn-fill btn-primary" type="submit">Crear</button>
            <a href="{{ url()->previous() }}">Regresar</a>
        </div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/area/edit.blade.php
@extends('layouts.master')
@section('contenido')
<div class="container">
    <div class="card">

        <div class="header">
            <h3> Editar Area  </h3>
        </div>
        <div class="card-body">

    @if($errors->any())
    <ul>
        @foreach($errors->all() as $error)
        <li class="text-danger">{{ $error }}</li>
        @endforeach
    </ul>

    @endif

    <form action="{{route('area.update',['area'=>$area->id])}}" method="POST" novalidate>
        {{Form::token()}}
        {{ method_field('PUT') }}
        @if(is_file(public_path('qr/'.$area->id.'.png')))
        <img src='{{asset('qr/'.$area->id.'.png')}}' style="height: 130px;">
        @endif                                <div class="form-group">
            <label for="codigo">Codigo</label>
                    <input class="form-control String"  type="text"  name="codigo" id="codigo" value="{{old('codigo',$area->codigo)}}"
                                    >
                    @if($errors->has('codigo'))
            <p class="text-danger">{{$errors->first('codigo')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="nombre">Nombre</label>
                    <input class="form-control String"  type="text"  name="nombre" id="nombre" value="{{old('nombre',$area->nombre)}}"
                                    >
                    @if($errors->has('nombre'))
            <p class="text-danger">{{$errors->first('nombre')}}</p>
            @endif
        </div>
                                <div class="form-group">
            <label for="detalle">Detalle</label>
                    <input class="form-control String"  type="text"  name="detalle" id="detalle" value="{{old('detalle',$area->detalle)}}"
                                    >
                    @if($errors->has('detalle'))
            <p class="text-danger">{{$errors->first('detalle')}}</p>
            @endif
        </div>
                        <div class="text-right">
            <button class="btn btn-fill btn-primary" type="submit">Guardar</button>
            <a href="{{ url()->previous() }}">Regresar</a>
        </div>
    </form>
    </div>
        </div>

</div>
@endsection

resources/views/area/index.blade.php
@extends('layouts.master')
@section('contenido')
<div class="container">

    @if(session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
    @endif
    <div class="card">
        <div class="header">
            <h3> Areas </h3>
        </div>
        <div class="card-body">

            <div style="padding-right: 30px;">
                <a href="{{route('area.create')}}" class="btn btn-fill btn-primary pull-right">Nuevo</a>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-striped">
                    @if(count($areas))
                    <thead>
                        <tr>
                            
                                                        
                                                                                    <td>Codigo</td>
                            
                                                                                    <td>Nombre</td>
                            
                                                                                    <td>Detalle</td>
                            
                                                        <th>&nbsp;</th>
                        </tr>

                    </thead>
                    @endif
                    <tbody>
                        @forelse($areas as $area)
                        <tr>
                            
                                                                                                                                            <td>{{$area->codigo}}</td>
                                                                                                                <td>{{$area->nombre}}</td>
                                                                                                                <td>{{$area->detalle}}</td>
                                                                                    <td>
                                <a href="{{route('area.show',['area'=>$area] )}}">Ver</a>
                                <a href="{{route('area.edit',['area'=>$area] )}}">Editar</a>
                                <a href="javascript:void(0)" onclick="event.preventDefault();
                                document.getElementById('delete-area-model-{{$area->id}}').submit();">
                                    Borrar
                                </a>
                                <form id="delete-area-model-{{$area->id}}" action="{{route('area.destroy',['area'=>$area])}}" method="POST" style="display: none;">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </td>

                        </tr>
                        @empty
                        <p>No Area Models</p>
                        @endforelse
                    </tbody>
                </table>
            </div>
            
        </div>
    </div>

</div>

@endsection

resources/views/area/show.blade.php
@extends('layouts.master')
@section('contenido')
<div class="container">

    <div class="card mb-4">

        <div class="header">
            <h3> Ver Area  </h3>
        </div>

    <div class="card-body">
                                        <div class="form-group">
            <label class="col-form-label" for="value">Codigo</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$area->codigo}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Nombre</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$area->nombre}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Detalle</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$area->detalle}}">
        </div>
                    </div>

    </div>

    <div class="card mb-4">

        
    </div>



    <a href="{{ url()->previous() }}">Regresar</a>
</div>
@endsection