routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::post('consultaRol','AuthenticateController@getRolUsuario')->name('consultaRol');//getRolUsuario
Route::post('Authenticate', 'AuthenticateController@Authenticate')->name('Authenticate');

Route::resource('usuarios', 'UsuarioController');
Route::resource('area', 'AreaController');
Route::get('ingreso-area', 'ingresoAreaController@index');
Route::any('ingreso-area/{user}', 'ingresoAreaController@historialIngresoUsuario')->name('historialIngresoUsuario');
Route::get('ingreso-area/lista/usuarios/{ingreso}', 'ingresoAreaController@listaUsuarioIngresoArea');

Route::group(['middleware' => 'jwt.auth'], function () {

	Route::post('ingreso/crear','ingresoAreaController@postIngreso');//getConsultaIngreso
	Route::post('ingreso/consulta','ingresoAreaController@getConsultaIngreso');//getConsultaIngreso
	Route::post('ingreso/consultaPersonal','ingresoAreaController@getConsultaPersonal');//getConsultaPersonal
	

});

app/UsuarioModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UsuarioModel extends Model
{
    protected $table = 'users';
    protected $primaryKey='id';
    public $timestamps = false;

    protected $fillable = [
		'name',
		'apellidos',
    'email',
    'cedula',
    'edad',
    'id_rol_usuario',
    'password',
		'remember_token',
    'covid'
    ];
    
    protected $hidden = [
		'password',
		'remember_token'
    ];
    
    public function rol()
    {
        return $this->belongsToMany(\App\RolModel::class, 'rol_usuario','id_usuario','id_rol');
    }

    public function getNombresAttribute()
    {
        return "{$this->name} {$this->apellidos}";
    }
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\UsuarioModelPostRequest;
use App\Http\Requests\UpdateUsuarioModelPostRequest;
use App\UsuarioModel;


class UsuarioController extends Controller
{

    public function index(Request $request)
    {
        $usuarios = UsuarioModel::all();

        if($request->ajax()){
            $param = $request->search;
            $fields = UsuarioModel::getModel()->getFillable();
            $usuarios = UsuarioModel::where(function($query) use($fields,$param){
                foreach ($fields as $field){
                    $query->orWhere('users.' . $field, 'like', '%'.$param .'%');
                }
            })->get();
            
            $table = '';
            foreach ($usuarios as $key => $usuario) {

                $table.='<tr>'.

                    '<td>'.$usuario->name.'</td>'.
                    '<td>'.$usuario->apellidos.'</td>'.
                    '<td>'.$usuario->email.'</td>'.
                    '<td>'.$usuario->cedula.'</td>'.
                    '<td>'.$usuario->edad.'</td>'.
                    '<td>'.$usuario->rol->map(function($rol) {
                            return "<span class='badge badge-primary'>".$rol->nombre."</span>";
                        })->implode('<br>').'</td>'.
                    '<td>'.
                        '<a href="'.url('ingreso-area/'.$usuario->id).'">Historial </a>'.
                        '<a href="'.route('usuarios.edit',['usuario'=>$usuario] ).'"> Editar</a>'.
                        '<a href="javascript:void(0)" onclick="event.preventDefault();'.
                        'document.getElementById("delete-usuario-model-'.$usuario->id.'").submit();">'.
                            ' Borrar'.
                        '</a>'.
                        '<form id="delete-usuario-model-'.$usuario->id.'" action="'.route('usuarios.destroy',['usuario'=>$usuario]).'" method="POST" style="display: none;">'.
                            
                        '</form>'.
                    '</td>'.
                
                '</tr>';
                
            }
            return Response($table);
        }
        return view('usuarios.index', compact('usuarios'));
    }

    public function show(Request $request, UsuarioModel $usuario)
    {
        return view('usuarios.show', compact('usuario'));
    }

    public function create()
    {
        return view('usuarios.create');
    }

    public function store(UsuarioModelPostRequest $request)
    {
        $data = $request->validated();
        $usuario = UsuarioModel::create($data);
        return redirect()->route('usuarios.index')->with('status', 'UsuarioModel created!');
    }

    public function edit(Request $request, UsuarioModel $usuario)
    {
        return view('usuarios.edit', compact('usuario'));
    }

    public function update(UpdateUsuarioModelPostRequest $request, UsuarioModel $usuario)
    {
        $data = $request->validated();
        $usuario->fill($data);
        $usuario->save();
        return redirect()->route('usuarios.index')->with('status', 'Usuarioss updated!');
    }

    public function destroy(Request $request, UsuarioModel $usuario)
    {
        $usuario->delete();
        return redirect()->route('usuarios.index')->with('status', 'Usuario destroyed!');
    }
}

resources/views/usuarios/create.blade.php
@extends('layouts.master')
@section('contenido')
<div class="container">
    <div class="card stacked-form">

        <div class="header">
            <h3 class="card-title"> Crear Usuario </h3>
        </div>
        <div class="card-body">

            @if($errors->any())
            <ul>
                @foreach($errors->all() as $error)
                <li class="text-danger">{{ $error }}</li>
                @endforeach
            </ul> 
            @endif 
            <form action="{{route('usuarios.store')}}" method="POST" novalidate>
                {{Form::token()}}
                <div class="form-group">
                <label for="name">Nombre</label>
                <input class="form-control String"  type="text"  name="name" id="name" value="{{old('name')}}"             maxlength="191"
                    required="required">
                @if($errors->has('name'))
                <p class="text-danger">{{$errors->first('name')}}</p>
                @endif
            </div>
                                    <div class="form-group">
                <label for="apellidos">Apellidos</label>
                            <input class="form-control String"  type="text"  name="apellidos" id="apellidos" value="{{old('apellidos')}}"             maxlength="255"
                                        >
                            @if($errors->has('apellidos'))
                <p class="text-danger">{{$errors->first('apellidos')}}</p>
                @endif
            </div>
                                    <div class="form-group">
                <label for="email">Email</label>
                            <input class="form-control String"  type="text"  name="email" id="email" value="{{old('email')}}"             maxlength="191"
                                        required="required"
                            >
                            @if($errors->has('email'))
                <p class="text-danger">{{$errors->first('email')}}</p>
                @endif
            </div>
                                    <div class="form-group">
                <label for="password">Password</label>
                            <input class="form-control String"  type="text"  name="password" id="password" value="{{old('password')}}"             maxlength="191"
                                        required="required"
                            >
                            @if($errors->has('password'))
                <p class="text-danger">{{$errors->first('password')}}</p>
                @endif
            </div>
                                    <div class="form-group">
                <label for="cedula">Cedula</label>
                            <input class="form-control String"  type="text"  name="cedula" id="cedula" value="{{old('cedula')}}"             maxlength="13"
                                        >
                            @if($errors->has('cedula'))
                <p class="text-danger">{{$errors->first('cedula')}}</p>
                @endif
            </div>
                                    <div class="form-group">
                <label for="edad">Edad</label>
                            <input class="form-control String"  type="text"  name="edad" id="edad" value="{{old('edad')}}"             maxlength="3"
                                        >
                            @if($errors->has('edad'))
                <p class="text-danger">{{$errors->first('edad')}}</p>
                @endif
            </div>
            
            <div class="form-group">
                <label for="id_rol_usuario">Rol Usuario</label>
                {!! Form::select('id_rol_usuario', App\RolModel::pluck('nombre','id'), old('id_rol_usuario'), ['class'=>'form-control']) !!}
                @if($errors->has('id_rol_usuario'))
                <p class="text-danger">{{$errors->first('id_rol_usuario')}}</p>
                @endif
            </div>
                                    
            <div class="text-right">
                <button class="btn btn-fill btn-primary" type="submit">Crear</button>
                <a href="{{ url()->previous() }}">Regresar</a>
            </div>
            </form>
        </div>
    </div>
    
</div>
@endsection

resources/views/usuarios/edit.blade.php
@extends('layouts.master')
@section('contenido')
<div class="container">
    <div class="card">

        <div class="header">
            <h3> Editar Usuario </h3>
        </div>
        <div class="card-body">

    @if($errors->any())
    <ul>
        @foreach($errors->all() as $error)
        <li class="text-danger">{{ $error }}</li>
        @endforeach
    </ul>

    @endif

    <form action="{{route('usuarios.update',['usuario'=>$usuario->id])}}" method="POST" novalidate>
        {{Form::token()}}
        {{ method_field('PUT') }}
        

        <div class="form-group">
            <label for="name">Nombre</label>
            <input class="form-control String"  type="text"  name="name" id="name" value="{{old('name',$usuario->name)}}"required="required">
            @if($errors->has('name'))
            <p class="text-danger">{{$errors->first('name')}}</p>
            @endif
        </div>
        <div class="form-group">
            <label for="apellidos">Apellidos</label>
            <input class="form-control String"  type="text"  name="apellidos" id="apellidos" value="{{old('apellidos',$usuario->apellidos)}}">
            @if($errors->has('apellidos'))
            <p class="text-danger">{{$errors->first('apellidos')}}</p>
            @endif
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control String"  type="text"  name="email" id="email" value="{{old('email',$usuario->email)}}"required="required">
            @if($errors->has('email'))
            <p class="text-danger">{{$errors->first('email')}}</p>
            @endif
        </div>
                                
        <div class="form-group">
            <label for="cedula">Cedula</label>
            <input class="form-control String"  type="text"  name="cedula" id="cedula" value="{{old('cedula',$usuario->cedula)}}">
            @if($errors->has('cedula'))
            <p class="text-danger">{{$errors->first('cedula')}}</p>
            @endif
        </div>
        <div class="form-group col-md-10">
            <label for="edad">Edad</label>
            <input class="form-control String"  type="text"  name="edad" id="edad" value="{{old('edad',$usuario->edad)}}">
            @if($errors->has('edad'))
            <p class="text-danger">{{$errors->first('edad')}}</p>
            @endif
        </div>
        
            <div class="form-group text-center col-md-2">
              {!! Form::label('covid', 'Enfermo') !!}
              <div class="">
                <label for="">
                  {!! Form::hidden('covid', 0, null) !!}
                  {!! Form::checkbox('covid', 1,$usuario->covid) !!}
                </label>
                
              </div>
              
            </div>
        
        <div class="form-group">
            <label for="id_rol_usuario">Rol Usuario</label>
            {!! Form::select('id_rol_usuario', App\RolModel::pluck('nombre','id'), old('id_rol_usuario',$usuario->id_rol_usuario), ['class'=>'form-control']) !!}
            @if($errors->has('id_rol_usuario'))
            <p class="text-danger">{{$errors->first('id_rol_usuario')}}</p>
            @endif
        </div>
                                
                                
        <div class="">
            <button class="btn btn-primary btn-fill" type="submit">Guardar</button>
            <a href="{{ url()->previous() }}" class="btn-default btn">Regresar</a>
        </div>
    </form>
    </div>
        </div>

</div>
@endsection

resources/views/usuarios/historial_area.blade.php
@extends('layouts.master')
@section('contenido')
<div class="container">

    @if(session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
    @endif
    <div class="card">
        <div class="header">
            <h3> Historial de Ingreso Areas de @if(count($ingreso_areas)){{$ingreso_areas->first()->usuario->nombres}}@endif </h3>
        </div>
        {!! Form::open(['route' => ['historialIngresoUsuario','userId' => $userId]]) !!}
        <div style="padding: 0 4px;" class="row">
            <div class="col-sm-6">
                <!-- Start date and time Field -->
                <div class="form-group ">
                    {!! Form::label('start_date', 'Fecha inicio', ['class' => 'control-label text-right']) !!}
                    <div class="col-6">
                        {!! Form::date('start_date', isset($start_date)?date("Y-m-d",strtotime($start_date)):null,  ['class' => 'form-control datepicker','autocomplete'=>'off','placeholder'=>  trans("lang.delivery_discount_star_date_time_placeholder")  ]) !!}
                    
                    </div>
                </div>
            </div>
            
            <div class="col-6">
                <!-- End date and time Field -->
                <div class="form-group col-6">
                    {!! Form::label('end_date', 'Fecha Fin', ['class' => 'control-label text-right']) !!}
                    <div class="col-sm-6">
                        {!! Form::date('end_date', isset($end_date)?date("Y-m-d",strtotime($end_date)):null,  ['class' => 'form-control datepicker','autocomplete'=>'off','placeholder'=>  trans("lang.delivery_discount_end_date_time_placeholder")  ]) !!}
                    
                    </div>
                </div>
            </div>
            

            

            <div class="col-sm-12 text-right">
                <button type="submit" class="btn btn-fill btn-primary ">Buscar <i class="fa fa-search"></i></button>
            </div>
            
        </div>
        {!! Form::close() !!}

        <div class="card-body">

            <div class="content table-responsive table-full-width">
                <table class="table table-striped">
                    @if(count($ingreso_areas))
                    <thead>
                        <tr>
                                                 
                            <th>Codigo</th>

                            <th>Area</th>

                            <th>Entrada  -  Salida </th>
                            <th>&nbsp;</th>
                            
                        </tr>

                    </thead>
                    @endif
                    <tbody>
                        @forelse($ingreso_areas as $ingreso_area)
                        <tr>
                            
                            <td>{{$ingreso_area->area->codigo}}</td>
                            <td>{{$ingreso_area->area->nombre}}</td>
                            <td>{{$ingreso_area->fecha_hora.'  -  '.fechaSalida($ingreso_area)}}</td>
                            <td><a href="{{url('ingreso-area/lista/usuarios/'.$ingreso_area->id)}} ">Lista de usuarios</a></td>
                            
                        </tr>
                        @empty
                        <p>No Ingreso Area</p>
                        @endforelse
                    </tbody>
                </table>
            </div>
            
        </div>
    </div>

</div>

@endsection

resources/views/usuarios/index.blade.php
@extends('layouts.master')
@section('contenido')
<div class="container">

    @if(session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
    @endif
    <div class="card">
        <div class="header">
            <h4 class="title">Usuarios</h4>
        </div>
        <div class="card-body">

            <div style="padding-right: 30px;">
                <div class="form-group">
                    <div class="col-3">
                        <input type="text" class="form-control pull-left" id="search" name="search" style="width: 30%" placeholder="Buscar usuario">
                    </div>
                               
                </div>
                <a href="{{route('usuarios.create')}}" class="btn btn-fill btn-primary pull-right">Nuevo</a>
            </div>
            <br><br>
            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped">
                    @if(count($usuarios))
                    <thead>
                        <tr>
                                            
                            <th>Nombres</th>

                            <th>Apellidos</th>

                            <th>Email</th>

                            <th>Cedula</th>

                            <th>Edad</th>

                            <th>Rol</th>

                            <th>&nbsp;</th>

                        </tr>

                    </thead>
                    @endif
                    <tbody>
                        @forelse($usuarios as $usuario)
                        <tr>
                            
                            <td>{{$usuario->name}}</td>
                            <td>{{$usuario->apellidos}}</td>
                            <td>{{$usuario->email}}</td>
                            <td>{{$usuario->cedula}}</td>
                            <td>{{$usuario->edad}}</td>
                            <td>{!!$usuario->rol->map(function($rol) {
                                return "<span class='badge badge-primary'>".$rol->nombre."</span>";
                            })->implode('<br>')!!}</td>
                            <td>
                                <a href="{{url('ingreso-area/'.$usuario->id)}} ">Historial</a>
                                <a href="{{route('usuarios.edit',['usuario'=>$usuario] )}}">Editar</a>
                                <a href="javascript:void(0)" onclick="event.preventDefault();
                                document.getElementById('delete-usuario-model-{{$usuario->id}}').submit();">
                                    Borrar
                                </a>
                                <form id="delete-usuario-model-{{$usuario->id}}" action="{{route('usuarios.destroy',['usuario'=>$usuario])}}" method="POST" style="display: none;">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </td>
                                                                                            
                        </tr>
                        @empty
                        <p>No hay Usuarios</p>
                        @endforelse
                    </tbody>
                </table> 
            </div>
            
        </div>
    </div>

</div>
@endsection

@section('page-js')
<script>
    $('#search').on('keyup',function(){

    $value=$(this).val();

    $.ajax({
        type : 'get',
        url : '{{URL::to('usuarios')}}',
        data:{'search':$value},
        success:function(data){
            $('tbody').html(data);
        }

    });



    })
</script>
@endsection

resources/views/usuarios/lista_usuarios_area.blade.php
@extends('layouts.master')
@section('contenido')
<div class="container">

    @if(session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
    @endif
    <div class="card">
        <div class="header">
            <h4 class="title">Lista de usuario en el area {{$ingreso_areas->area->nombre}}</h4>
        </div>
        <div class="card-body">

            <div style="padding-right: 30px;">
                <a href="{{route('usuarios.create')}}" class="btn btn-fill btn-primary pull-right">Nuevo</a>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped">
                    @if(count($usuarios))
                    <thead>
                        <tr>
                                            
                            <th>Nombres</th>

                            <th>Apellidos</th>

                            <th>Email</th>

                            <th>Cedula</th>

                            <th>Edad</th>

                            <th>Rol</th>

                            <th>&nbsp;</th>

                        </tr>

                    </thead>
                    @endif
                    <tbody>
                        @forelse($usuarios as $usuario)
                        <tr>
                            
                            <td>{{$usuario->name}}</td>
                            <td>{{$usuario->apellidos}}</td>
                            <td>{{$usuario->email}}</td>
                            <td>{{$usuario->cedula}}</td>
                            <td>{{$usuario->edad}}</td>
                            <td>
                                @isset($usuario->rol)
                                {!!$usuario->rol->map(function($rol) {
                                    return "<span class='badge badge-primary'>".$rol->nombre."</span>";
                                })->implode('<br>')!!}
                                @endisset
                            </td>
                            <td>
                               
                            </td>
                                                                                            
                        </tr>
                        @empty
                        <p>No hay Usuarios</p>
                        @endforelse
                    </tbody>
                </table> 
            </div>
            
        </div>
    </div>

</div>

@endsection

resources/views/usuarios/show.blade.php
@extends('layouts.master')
@section('contenido')
<div class="container">

    <div class="card mb-4">

        <div class="card-header">
            <h1> Ver Usuario Model  </h1>
        </div>

    <div class="card-body">
                                        <div class="form-group">
            <label class="col-form-label" for="value">Name</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$usuario->name}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Apellidos</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$usuario->apellidos}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Email</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$usuario->email}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Password</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$usuario->password}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Cedula</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$usuario->cedula}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Edad</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$usuario->edad}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Id Rol Usuario</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$usuario->id_rol_usuario}}">
        </div>
                                <div class="form-group">
            <label class="col-form-label" for="value">Remember Token</label>
            <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$usuario->remember_token}}">
        </div>
                                                                    </div>

    </div>

    <div class="card mb-4">

        
    </div>



    <a href="{{ url()->previous() }}">Regresar</a>
</div>
@endsection